const gameData = {
  win: window,
  mainContainer: document.querySelector('.main'),
  player: document.getElementById('player'),
  enemyModel: document.getElementById('enemy'),
  attackButton: document.getElementById('attack'),
  specialButton: document.getElementById('special'),
  defendButton: document.getElementById('defend'),
  playerAdvantageButton: document.getElementById('player-advantage'),
  playerHealthButton: document.getElementById('player-give-health'),
  enemyAdvantageButton: document.getElementById('enemy-advantage'),
  enemyHealthButton: document.getElementById('enemy-give-health'),
  enemyAttack: document.getElementById('e-attack'),
  enemySpecial: document.getElementById('e-special'),
  enemyDefend: document.getElementById('e-defend'),
  playerCanvas: document.getElementById('player-canvas'),
  enemyCanvas: document.getElementById('enemy-canvas'),
}